version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/github-clarkritchie"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/s3-remote-state"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/s3-static-hosting"
    schedule:
      interval: "weekly"
